import "./globals.css";
import Header from './components/Header'
import Footer from './components/Footer'
export const metadata = {
  title: "Iptvego",
  description: "Generated by create next app",
  themeColor : "#0f0f0f",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
